### ISSUE TITLE
Apparent boost dependency problem

### ISSUE THREAD

**Issue by EelcoHoogendoorn** [ClinicalGraphics/pyopcode#9]
```
Traceback (most recent call last):
  File ".../render.py", line 5, in <module>
    import pyopcode
  File ".../lib/python3.6/site-packages/pyopcode/__init__.py", line 5, in <module>
    from _pyopcode import Model, Collision
ImportError: dlopen(.../lib/python3.6/_pyopcode.so, 2): Library not loaded: @rpath/libboost_python.dylib
  Referenced from: .../lib/python3.6/_pyopcode.so
  Reason: no suitable image found.  Did find:
	.../lib/libpython3.6m.dylib/libboost_python.dylib: stat() failed with errno=20

```
Get the following error trying to use the clinicalgraphics 0.3.4 OSX package. The one on cpbotha's channel works fine.

**Comment by Korijn** [comment]
Right off the bat I can tell you we moved to support only pypi linux wheels for python 3.6

**Comment by Korijn** [comment]
Sorry for the brief reply yesterday, I was in a hurry.

We've stopped using the conda package manager and decided to make a one-time effort to move and update our recipes to conda-forge so the community can still leverage our new setuptools based packages.

So the primary conda recipe now lives at https://github.com/conda-forge/pyopcode-feedstock and any issues with it should be reported and handled there.

**Comment by EelcoHoogendoorn** [comment]
Ok, thanks; ill see if I can add an OSX build to conda-forge then if the need re-arises.
